name: root
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - folium
  - ipkernel
  - requests
  - matplotlib
  - pandas
  - pip:
    - git+https://github.com/pyoceans/erddapy.git
